import json, sys
sys.stdout.reconfigure(encoding='utf-8')

cell_lines = [
    "# \u2500\u2500 9. Regenerate Dashboard HTML \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\n",
    "# Splices fresh data into dashboard.html between @@DATA_START@@ / @@DATA_END@@ markers.\n",
    "# Run this cell every time you refresh the input data.\n",
    "\n",
    "import json as _json, re as _re, numpy as _np, pathlib as _pathlib\n",
    "from datetime import date as _date\n",
    "\n",
    "def _j(v):\n",
    "    if isinstance(v, _np.integer): return int(v)\n",
    "    if isinstance(v, _np.floating): return float(v)\n",
    "    return v\n",
    "\n",
    "def _summary_rows(df):\n",
    "    rows = []\n",
    "    for _, r in df.sort_values('Total Open Claims', ascending=False).iterrows():\n",
    "        rows.append({\n",
    "            'wh':    str(r['Warehouse']),\n",
    "            'lt30':  _j(r['<30 days']),\n",
    "            'd30':   _j(r['30-<60 days']),\n",
    "            'd60':   _j(r['60-<90 days']),\n",
    "            'ge90':  _j(r['>= 90 days']),\n",
    "            'total': _j(r['Total Open Claims']),\n",
    "            'pct90': round(float(r['% >= 90 days']) * 100, 1) if r['Total Open Claims'] > 0 else 0,\n",
    "        })\n",
    "    return rows\n",
    "\n",
    "def _oldest_rows(dataset_name, n=10):\n",
    "    import pandas as _pd\n",
    "    df = combined_all.copy()\n",
    "    open_df = df[(df['Dataset'] == dataset_name) & (df['Progress'] != 'Completed')].copy()\n",
    "    open_df['Start Date'] = _pd.to_datetime(open_df['Start Date'], errors='coerce')\n",
    "    today = _pd.Timestamp('today').normalize()\n",
    "    open_df['days_open'] = (today - open_df['Start Date']).dt.days\n",
    "    top = open_df.sort_values('days_open', ascending=False).head(n)\n",
    "    rows = []\n",
    "    for _, r in top.iterrows():\n",
    "        parts = str(r['Task Name']).split(' - ')\n",
    "        label = ' \u2013 '.join(parts[:3]) if len(parts) >= 3 else str(r['Task Name'])[:70]\n",
    "        rows.append({\n",
    "            'task':      label,\n",
    "            'warehouse': str(r['Warehouse']),\n",
    "            'days':      int(r['days_open']) if _pd.notna(r['days_open']) else 0,\n",
    "            'start':     str(r['Start Date'])[:10] if _pd.notna(r['Start Date']) else '',\n",
    "        })\n",
    "    return rows\n",
    "\n",
    "def _action_rows(dataset_name):\n",
    "    rows = []\n",
    "    sub = open_tasks_agg[open_tasks_agg['Dataset'] == dataset_name].sort_values('Count', ascending=False)\n",
    "    for _, r in sub.iterrows():\n",
    "        rows.append({'wh': str(r['Warehouse']), 'action': str(r['Action Required']), 'count': _j(r['Count'])})\n",
    "    return rows\n",
    "\n",
    "ford_sum   = _summary_rows(aging_summary[aging_summary['Dataset'] == 'Ford Claims'])\n",
    "chrys_sum  = _summary_rows(aging_summary[aging_summary['Dataset'] == 'Chrysler Claims'])\n",
    "ford_old   = _oldest_rows('Ford Claims')\n",
    "chrys_old  = _oldest_rows('Chrysler Claims')\n",
    "ford_acts  = _action_rows('Ford Claims')\n",
    "chrys_acts = _action_rows('Chrysler Claims')\n",
    "\n",
    "ford_total        = sum(r['total'] for r in ford_sum)\n",
    "chrys_total       = sum(r['total'] for r in chrys_sum)\n",
    "ford_ge90         = sum(r['ge90']  for r in ford_sum)\n",
    "chrys_ge90        = sum(r['ge90']  for r in chrys_sum)\n",
    "ford_biggest      = max(ford_sum,  key=lambda r: r['total'])\n",
    "chrys_biggest     = max(chrys_sum, key=lambda r: r['total'])\n",
    "ford_oldest_days  = max((r['days'] for r in ford_old),  default=0)\n",
    "chrys_oldest_days = max((r['days'] for r in chrys_old), default=0)\n",
    "ford_oldest_wh    = next((r['warehouse'] for r in ford_old  if r['days'] == ford_oldest_days),  '')\n",
    "chrys_oldest_wh   = next((r['warehouse'] for r in chrys_old if r['days'] == chrys_oldest_days), '')\n",
    "\n",
    "as_of = _date.today().strftime('%B %d, %Y')\n",
    "\n",
    "data_js = '\\n'.join([\n",
    "    f'const AS_OF         = {_json.dumps(as_of)};',\n",
    "    f'const fordSummary   = {_json.dumps(ford_sum,   indent=2)};',\n",
    "    f'const chrysSummary  = {_json.dumps(chrys_sum,  indent=2)};',\n",
    "    f'const fordOldest    = {_json.dumps(ford_old,   indent=2)};',\n",
    "    f'const chrysOldest   = {_json.dumps(chrys_old,  indent=2)};',\n",
    "    f'const fordActions   = {_json.dumps(ford_acts,  indent=2)};',\n",
    "    f'const chrysActions  = {_json.dumps(chrys_acts, indent=2)};',\n",
    "    f'const fordTotal     = {ford_total};',\n",
    "    f'const chrysTotal    = {chrys_total};',\n",
    "    f'const fordGe90      = {ford_ge90};',\n",
    "    f'const chrysGe90     = {chrys_ge90};',\n",
    "    f'const fordBiggestWh = {_json.dumps(ford_biggest[\"wh\"])};',\n",
    "    f'const fordBiggestN  = {ford_biggest[\"total\"]};',\n",
    "    f'const chrysBiggestWh= {_json.dumps(chrys_biggest[\"wh\"])};',\n",
    "    f'const chrysBiggestN = {chrys_biggest[\"total\"]};',\n",
    "    f'const fordOldestDays  = {ford_oldest_days};',\n",
    "    f'const fordOldestWh    = {_json.dumps(ford_oldest_wh)};',\n",
    "    f'const chrysOldestDays = {chrys_oldest_days};',\n",
    "    f'const chrysOldestWh   = {_json.dumps(chrys_oldest_wh)};',\n",
    "])\n",
    "\n",
    "replacement = '// @@DATA_START@@\\n' + data_js + '\\n// @@DATA_END@@'\n",
    "dash_path = _pathlib.Path(OUT_XLSX).parent / 'dashboard.html'\n",
    "html = dash_path.read_text(encoding='utf-8')\n",
    "html = _re.sub(\n",
    "    r'// @@DATA_START@@.*?// @@DATA_END@@',\n",
    "    lambda _m: replacement,\n",
    "    html, flags=_re.DOTALL\n",
    ")\n",
    "dash_path.write_text(html, encoding='utf-8')\n",
    "print(f'Dashboard updated: {dash_path}')\n",
]

with open('Claims_Aging_Pareto_v3.2_commented.ipynb', encoding='utf-8') as f:
    nb = json.load(f)

# Remove previously added cell if re-running this script
if len(nb['cells']) > 8:
    last_src = ''.join(nb['cells'][-1].get('source', []))
    if 'Regenerate Dashboard HTML' in last_src:
        nb['cells'].pop()

new_cell = {
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": cell_lines
}

nb['cells'].append(new_cell)

with open('Claims_Aging_Pareto_v3.2_commented.ipynb', 'w', encoding='utf-8') as f:
    json.dump(nb, f, ensure_ascii=False, indent=1)

print(f"Done. Notebook now has {len(nb['cells'])} cells.")
